import { requireUser } from "@/lib/auth";
import { SiteHeader } from "@/components/site-header";
import { query } from "@/lib/db";
import { formatBRL, getCommercialSettings } from "@/lib/commercial";
import { saveCommercialSettings } from "./actions";

export const dynamic = "force-dynamic";
export default async function Backoffice() {
  const user = await requireUser("/backoffice");
  if (user.role !== "admin") return <main className="page"><SiteHeader/><div className="content page-hero"><h1>Área restrita</h1><p>Sua conta não possui acesso administrativo.</p></div></main>;
  const [counts, suggestions, prices] = await Promise.all([
    query<{members:string;starts:string;completed:string;feedbacks:string;partners:string;suggestions:string}>(`SELECT (SELECT COUNT(*) FROM users)::text AS members,(SELECT COUNT(*) FROM learning_progress)::text AS starts,(SELECT COUNT(*) FROM learning_progress WHERE completed=TRUE)::text AS completed,(SELECT COUNT(*) FROM feedback)::text AS feedbacks,(SELECT COUNT(*) FROM partner_leads)::text AS partners,(SELECT COUNT(*) FROM work_suggestions)::text AS suggestions`),
    query<{title:string;author:string|null;reason:string;email:string|null;created_at:Date}>("SELECT title,author,reason,email,created_at FROM work_suggestions ORDER BY created_at DESC LIMIT 50"),
    getCommercialSettings(),
  ]);
  const c = counts.rows[0];
  const metrics = [["Membros cadastrados",c.members],["Experiências iniciadas",c.starts],["Experiências concluídas",c.completed],["Sugestões de obras",c.suggestions]];
  return <main className="backoffice"><SiteHeader/><div className="content"><section className="backoffice-hero"><span className="section-kicker">BACKOFFICE · VALIDAÇÃO</span><h1>O que aprendemos antes de cobrar.</h1><p>Feedbacks: <strong>{c.feedbacks}</strong>. Parceiros interessados: <strong>{c.partners}</strong>.</p></section><section className="metrics">{metrics.map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="dashboard-grid"><article className="dashboard-card"><h2>Preços de referência</h2><p>Os números aparecem riscados no catálogo enquanto o acesso estiver gratuito. Alterar aqui não ativa cobranças.</p><form action={saveCommercialSettings} className="form-card"><div className="field"><label htmlFor="single-price">Obra individual (R$)</label><input id="single-price" name="single_price" type="number" min="0" max="10000" step="0.01" defaultValue={(prices.single_price_cents/100).toFixed(2)} required /></div><div className="field"><label htmlFor="club-price">Coonto Club por mês (R$)</label><input id="club-price" name="club_price" type="number" min="0" max="10000" step="0.01" defaultValue={(prices.club_price_cents/100).toFixed(2)} required /></div><button type="submit" className="button button-primary">Salvar preços</button></form><p>Atualmente: {formatBRL(prices.single_price_cents)} por obra e {formatBRL(prices.club_price_cents)}/mês.</p></article><article className="dashboard-card"><h2>Catálogo inicial</h2><p><strong>O Alienista</strong> está disponível para validação. <strong>Dom Casmurro</strong> e <strong>Memórias Póstumas de Brás Cubas</strong> aparecem em preparação. O Club só será lançado como produto com as três experiências concluídas e revisadas.</p><p>O preço mostrado é uma referência; a integração de pagamentos segue desativada.</p></article></section><section className="dashboard-card" style={{marginBottom:80}}><h2>Sugestões recentes de obras</h2>{suggestions.rows.length ? <div className="status-list">{suggestions.rows.map((item,index)=><article className="status-item" key={index}><div><strong>{item.title}</strong>{item.author && <span> · {item.author}</span>}<p>{item.reason}</p><small>{new Date(item.created_at).toLocaleDateString("pt-BR")}{item.email && <> · {item.email}</>}</small></div></article>)}</div> : <p>Ainda não há sugestões.</p>}</section></div></main>;
}
