import { BookOpen, Cloud, ShieldCheck } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { DeviceManager } from "@/components/device-manager";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { query } from "@/lib/db";
import { ALIENISTA_SLUG, ensureAlienistaEntitlement, getMember } from "@/lib/member";

export const dynamic="force-dynamic";
export default async function MinhaBiblioteca(){const user=await requireUser("/minha-biblioteca");await getMember();await ensureAlienistaEntitlement(user.userId);const [progressResult,deviceResult]=await Promise.all([query<{percent:number;completed:boolean}>("SELECT percent,completed FROM learning_progress WHERE user_id=$1 AND work_slug=$2 LIMIT 1",[user.userId,ALIENISTA_SLUG]),query<{id:string;label:string;last_seen_at:string}>("SELECT id,label,last_seen_at FROM member_devices WHERE user_id=$1 AND revoked=FALSE ORDER BY last_seen_at DESC",[user.userId])]);const progress=progressResult.rows[0];return <main className="page"><SiteHeader/><div className="content member-page"><section className="member-welcome"><span className="section-kicker">MINHA CONTA COONTO</span><h1>Olá, {user.displayName.split(" ")[0]||user.email.split("@")[0]}.</h1><p>Sua leitura pessoal, seu progresso e os aparelhos autorizados ficam juntos aqui.</p><p>Prepara aulas? <a href="/professor">Acesse o espaço do professor</a>. Suas marcações de aula não alteram a leitura pessoal.</p></section><section className="member-grid"><article className="library-work"><div className="library-cover"><span>MACHADO DE ASSIS</span><strong>O Alienista</strong><small>Primeira experiência Coonto</small></div><div className="library-copy"><span className="status-pill">ACESSO ATIVO · VALIDAÇÃO</span><h2>{progress?(progress.completed?"Experiência concluída":"Continue de onde parou"):"Sua primeira experiência está pronta"}</h2><p>{progress?`${progress.percent}% da jornada percorrida. Seu histórico está sincronizado entre os aparelhos autorizados.`:"Entre em Itaguaí, decida, descubra e compreenda a obra por dentro."}</p><div className="member-progress"><span style={{width:`${progress?.percent??0}%`}}/></div><a className="button button-primary" href="/leitura/o-alienista"><BookOpen size={18}/>{progress?"Continuar experiência":"Começar agora"}</a></div></article><aside className="account-side"><section><h2><Cloud size={20}/> Histórico sincronizado</h2><p>Suas decisões e seu ponto de leitura acompanham sua conta.</p></section><section><h2><ShieldCheck size={20}/> Uso offline protegido</h2><p>Autorize até dois aparelhos. A obra fica disponível por 30 dias antes de renovar o acesso.</p><DeviceManager initialDevices={deviceResult.rows.map(device=>({id:device.id,label:device.label,lastSeenAt:String(device.last_seen_at)}))}/></section></aside></section></div><SiteFooter/></main>;}

